# Generated by Django 2.1.5 on 2019-01-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181228_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Услуга активна'),
        ),
    ]
