# Generated by Django 2.1.4 on 2018-12-26 18:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('photo', models.ImageField(default='../static/images/not_found.jpg', upload_to='services/%Y', verbose_name='Картинка услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Цена услуги')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('active', models.BooleanField(default=True, verbose_name='Услуга активна')),
                ('bids', models.ManyToManyField(blank=True, related_name='service_bid', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_created', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('-updated',),
            },
        ),
    ]
