# Generated by Django 2.1.4 on 2018-12-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='../static/images/defaultImage.png', upload_to='services/%Y', verbose_name='Картинка услуги'),
        ),
    ]
